import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/sage-wallet-rpc-api",
    },
    {
      type: "category",
      label: "NFTs",
      items: [
        {
          type: "doc",
          id: "api/add-nft-uri",
          label: "Add Nft Uri",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assign-nfts-to-did",
          label: "Assign Nfts To Did",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/bulk-mint-nfts",
          label: "Bulk Mint Nfts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-nft",
          label: "Get Nft",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-nft-collection",
          label: "Get Nft Collection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-nft-collections",
          label: "Get Nft Collections",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-nft-data",
          label: "Get Nft Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-nft-icon",
          label: "Get Nft Icon",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-nft-thumbnail",
          label: "Get Nft Thumbnail",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-nfts",
          label: "Get Nfts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/redownload-nft",
          label: "Redownload Nft",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/transfer-nfts",
          label: "Transfer Nfts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-nft",
          label: "Update Nft",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-nft-collection",
          label: "Update Nft Collection",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Peers",
      items: [
        {
          type: "doc",
          id: "api/add-peer",
          label: "Add Peer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-peers",
          label: "Get Peers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-peer",
          label: "Remove Peer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/set-discover-peers",
          label: "Set Discover Peers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/set-target-peers",
          label: "Set Target Peers",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "CAT Tokens",
      items: [
        {
          type: "doc",
          id: "api/auto-combine-cat",
          label: "Auto Combine Cat",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/bulk-send-cat",
          label: "Bulk Send Cat",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-all-cats",
          label: "Get All Cats",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-cats",
          label: "Get Cats",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-token",
          label: "Get Token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/issue-cat",
          label: "Issue Cat",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/resync-cat",
          label: "Resync Cat",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/send-cat",
          label: "Send Cat",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-cat",
          label: "Update Cat",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "XCH Transactions",
      items: [
        {
          type: "doc",
          id: "api/auto-combine-xch",
          label: "Auto Combine Xch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/bulk-send-xch",
          label: "Bulk Send Xch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/combine",
          label: "Combine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/multi-send",
          label: "Multi Send",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/send-xch",
          label: "Send Xch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/split",
          label: "Split",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Offers",
      items: [
        {
          type: "doc",
          id: "api/cancel-offer",
          label: "Cancel Offer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/cancel-offers",
          label: "Cancel Offers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/combine-offers",
          label: "Combine Offers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-offer",
          label: "Delete Offer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-offer",
          label: "Get Offer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-offers",
          label: "Get Offers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-offers-for-asset",
          label: "Get Offers For Asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/import-offer",
          label: "Import Offer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/make-offer",
          label: "Make Offer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/take-offer",
          label: "Take Offer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/view-offer",
          label: "View Offer",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Addresses",
      items: [
        {
          type: "doc",
          id: "api/check-address",
          label: "Check Address",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-derivations",
          label: "Get Derivations",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/increase-derivation-index",
          label: "Increase Derivation Index",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/set-change-address",
          label: "Set Change Address",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "DIDs",
      items: [
        {
          type: "doc",
          id: "api/create-did",
          label: "Create Did",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-dids",
          label: "Get Dids",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-minter-did-ids",
          label: "Get Minter Did Ids",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/normalize-dids",
          label: "Normalize Dids",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/transfer-dids",
          label: "Transfer Dids",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-did",
          label: "Update Did",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "System & Sync",
      items: [
        {
          type: "doc",
          id: "api/delete-database",
          label: "Delete Database",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-database-stats",
          label: "Get Database Stats",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-sync-status",
          label: "Get Sync Status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-version",
          label: "Get Version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/perform-database-maintenance",
          label: "Perform Database Maintenance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/resync",
          label: "Resync",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication & Keys",
      items: [
        {
          type: "doc",
          id: "api/delete-key",
          label: "Delete Key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-mnemonic",
          label: "Generate Mnemonic",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-key",
          label: "Get Key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-keys",
          label: "Get Keys",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-secret-key",
          label: "Get Secret Key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/import-key",
          label: "Import Key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/login",
          label: "Login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/logout",
          label: "Logout",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/rename-key",
          label: "Rename Key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/set-wallet-emoji",
          label: "Set Wallet Emoji",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Themes",
      items: [
        {
          type: "doc",
          id: "api/delete-user-theme",
          label: "Delete User Theme",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-user-theme",
          label: "Get User Theme",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-user-themes",
          label: "Get User Themes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/save-user-theme",
          label: "Save User Theme",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Options",
      items: [
        {
          type: "doc",
          id: "api/exercise-options",
          label: "Exercise Options",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-option",
          label: "Get Option",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-options",
          label: "Get Options",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/mint-option",
          label: "Mint Option",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/transfer-options",
          label: "Transfer Options",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-option",
          label: "Update Option",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Coins",
      items: [
        {
          type: "doc",
          id: "api/get-are-coins-spendable",
          label: "Get Are Coins Spendable",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-coins",
          label: "Get Coins",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-coins-by-ids",
          label: "Get Coins By Ids",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-spendable-coin-count",
          label: "Get Spendable Coin Count",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Network Settings",
      items: [
        {
          type: "doc",
          id: "api/get-network",
          label: "Get Network",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-networks",
          label: "Get Networks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/set-delta-sync",
          label: "Set Delta Sync",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/set-delta-sync-override",
          label: "Set Delta Sync Override",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/set-network",
          label: "Set Network",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/set-network-override",
          label: "Set Network Override",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Transactions",
      items: [
        {
          type: "doc",
          id: "api/get-pending-transactions",
          label: "Get Pending Transactions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-transaction",
          label: "Get Transaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-transactions",
          label: "Get Transactions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/sign-coin-spends",
          label: "Sign Coin Spends",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/submit-transaction",
          label: "Submit Transaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/view-coin-spends",
          label: "View Coin Spends",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Assets",
      items: [
        {
          type: "doc",
          id: "api/is-asset-owned",
          label: "Is Asset Owned",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
